name: Daily Insight Update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: pip install requests
    - name: Generate insight
      run: python generate_insight.py
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"
    - name: Build site
      run: hugo --minify
    - name: Commit and push to main
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Update site with new insight" || echo "No changes to commit"
        git push origin main