name: Daily Insight Update
on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 運行
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true  # 確保克隆主題
    - name: Check generated file
      run: cat content/posts/insight-*.md || echo "No insight file found"
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"
    - name: Build site
      run: hugo --minify
    - name: Check built site
      run: ls -l docs/ && test -f docs/index.html && echo "index.html exists" || echo "index.html missing"
    - name: Commit and push to main
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add docs/ content/posts/
        git commit -m "Update site with new insight" || echo "No changes to commit"
        git stash
        git pull origin main
        git push origin main